apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.mediacontrols'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()

android {
  namespace "expo.modules.mediacontrols"
  compileSdkVersion 35

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 35
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${rootProject.ext.kotlinVersion}"
  implementation "androidx.media:media:1.7.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
}
