name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels:
  - ["❌ bug"]
projects:
  - ["streamyfin/3"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: device
    attributes:
      label: Which device and operating system are you using?
      description: e.g. iPhone 15, iOS 18.1.1
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Streamyfin are you running?
      options:
        - 0.27.0
        - 0.26.1
        - 0.26.0
        - 0.25.0
        - 0.24.0
        - 0.23.0
        - 0.22.0
        - 0.21.0
        - older
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: If applicable, please add screenshots to help explain your problem.
        You can drag and drop images here or paste them directly into the comment box.
