blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://discord.streamyfin.app
    about: This issue tracker is not for support questions. Please refer to the StreamyFin community channels for help.