name: Android APK Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Android APK

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # @todo: update to 1.x once this is fixed: https://github.com/streamyfin/streamyfin/pull/690#discussion_r2089749689
          bun-version: 1.2.13

      - name: Setup Java for Android builds
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: |
          bun i && bun run submodule-reload

      - name: Cache android prebuild
        uses: actions/cache@v4
        with:
          key:
            bun-prebuild-${{ hashFiles('bun.lock') }}
          path: |
            ./android/

      - name: Generate project files
        run: |
          bun run prebuild

      - name: Build APK
        run: |
          bun run build:android:local

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamyfin-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Comment APK download link on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const artifactUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Android APK build completed successfully!\n\n[Download APK](${ artifactUrl })`
            });