name: Check Lockfile

on:
  pull_request:
  push:
    branches: [ develop, master ]

jobs:
  check-lockfile:
    name: Check for discrepancies between bun.lock and package.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          # @todo: update to 1.x once this is fixed: https://github.com/streamyfin/streamyfin/pull/690#discussion_r2089749689
          bun-version: 1.2.13

      - name: Check bun.lock and package.json consistency
        run: bun i --frozen-lockfile --dry-run --ignore-scripts 