name: 🛎️ Discord Pull Request Notification

on:
  pull_request:
    types: [opened, reopened]
    branches: [develop]

jobs:
  notify:
    runs-on: ubuntu-24.04
    steps:
      - name: 🛎️ Notify Discord
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # 0.4.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/193271640
        with:
          args: |
            📢 New Pull Request in **${{ github.repository }}**
            **Title:** ${{ github.event.pull_request.title }}
            **By:** ${{ github.event.pull_request.user.login }}
            **Branch:** ${{ github.event.pull_request.head.ref }}
            🔗 ${{ github.event.pull_request.html_url }}
